# Generated by Django 3.0.2 on 2020-01-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_detaisl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detaisl',
            new_name='Details',
        ),
    ]
